### ISSUE TITLE
Json2Array broke mutlistring message handling.

### ISSUE THREAD

**Issue by vevsvevs** [topkecleon/telegram-bot-bash#133] opened 2020-06-23 16:52 UTC
**Describe the bug**
New Json2Array sed regex pattern doesn't work well with multi-string messages. 

**To Reproduce**
Send any multi-string message to the bot and try to see MESSAGE contain.

**Expected behavior**
MESSAGE should contain the whole text.

**Screenshots**

**Bashbot (please complete the following information):**
 - Version: v0.96-0-g3871ca9
 - OS: 4.4.0-169-generic #198-Ubuntu SMP
 - Shell: GNU bash, version 4.3.48(1)-release

**Additional context**

**Comment by gnadelwartz** [comment] 2020-06-23 18:44
can you provide an example JSON content of a multistring message, then I can have a look at the problem.

**Comment by vevsvevs** [comment] 2020-06-24 09:49
Do you mean smth like this?
```
["ok"]	true
["result",0,"update_id"]	115013438
["result",0,"message","message_id"]	1585
["result",0,"message","from","id"]	558398329
["result",0,"message","from","is_bot"]	false
["result",0,"message","from","first_name"]	"vevs"
["result",0,"message","from","username"]	"vevsvevs"
["result",0,"message","from","language_code"]	"ru"
["result",0,"message","chat","id"]	558398329
["result",0,"message","chat","first_name"]	"vevs"
["result",0,"message","chat","username"]	"vevsvevs"
["result",0,"message","chat","type"]	"private"
["result",0,"message","date"]	1592991924
["result",0,"message","text"]	"string 1
string 2
string 3"
```

**Comment by gnadelwartz** [comment] 2020-06-24 10:20
Ok, I see, usually Telegram send this as:
["result",0,"message","text"] "string1\nstring2\nstring3"

I'll have a look

**Comment by gnadelwartz** [comment] 2020-06-24 10:24
if I send my bot

test1
test2
test3

if got:
["result",0,"message","text"]"test1\ntest2\ntest3"

**Comment by vevsvevs** [comment] 2020-06-25 00:14
By writing several words followed by "enter" :) Tested with 2.1.13 desktop and 6.2.0 (1988) Android versions, same result: I get linefeed (newline), not "\n". Maybe you're using non-Unicode client implementation or smth?

**Comment by gnadelwartz** [comment] 2020-06-25 05:26
thats really strange, if've test it with with Abdroid 6.2.0 and Telegram web and I got "test\ntest\ntest\n".

Nevertheless I'll try to implement a solution ...

**Comment by gnadelwartz** [comment] 2020-06-25 11:41
even I cannot reproduce it, I implemented a solution to "merge" multiline strings in one line.

to investigate further: pls open a chat with my bot user `@Deal_O_Mat_bot` name `DealOMat` and send a multi line message like you described:

```
multi
line
test
Gnadelwartz
```

then I can  consult my logfiles to see if I find more information about your issue

**Comment by vevsvevs** [comment] 2020-06-25 15:49
> to investigate further: pls open a chat with my bot user `@Deal_O_Mat_bot` name `DealOMat` and send a multi line message like you described:

Done, please check.

**Comment by gnadelwartz** [comment] 2020-06-25 22:15
thanks for this, unfortunately my bot was down this afternoon because of connection problems, can you repeat the test again, pls

**Comment by vevsvevs** [comment] 2020-06-25 22:51
@gnadelwartz sure, done :)

**Comment by gnadelwartz** [comment] 2020-06-26 06:06
thanks, the result is the same as with my tests:

["result",0,"message","text"]   "multi\nline\ntest\nGnadelwartz"

I see two possibilities for this:

- the used telegram server has small differences in implementaion
- strings changed by accident, e.g. deep packed inspection by provider or country 

nevertheless, the fix should hopefully make bashbot working for you. try current master.

**Comment by vevsvevs** [comment] 2020-06-26 21:27
@gnadelwartz yep, now it works perfectly, thank you!

**Comment by vevsvevs** [comment] 2020-07-08 14:18
Sorry for disturbing, but I've faced probably a related issue: now multi-string **replies** don't handle properly.

**Comment by vevsvevs** [comment] 2020-07-08 14:44
Also, seems like something is wrong with the debug feature: bashbot.log collects every message without debug option, and no log file created at all with this option.

**Comment by gnadelwartz** [comment] 2020-07-09 06:09
bashbot shoild log every activity (with the first 50 char of the message text) in all cases.

the difference is: with debug errors und additionally logging is done in debug log and full message content is logged in message log.

I'll check what's happen with and without debug in a fresh Installation

**Comment by gnadelwartz** [comment] 2020-07-09 10:37
> Sorry for disturbing, but I've faced probably a related issue: now multi-string **replies** don't handle properly.

hm, really strange, your Telegram server seems to handle Multiline totally different than the one used for my bot. where are you located?

so for example what's te result if send a message like

```
send_normal_message "CHAT[ID]" "This is\na muli line\nmessage"

or

send_normal_message "CHAT[ID]" "This is
a muli line
message"
```

**Comment by gnadelwartz** [comment] 2020-07-09 11:00
https://github.com/topkecleon/telegram-bot-bash/blob/487deee08cd4e69cb6ad537cfcfefdf8e3cf75a0/modules/sendMessage.sh#L32

try if it's working better uf you comment out this line

**Comment by vevsvevs** [comment] 2020-07-11 02:03
Sorry for the delay, I have some trouble, I'll try to check in next couple days.

**Comment by gnadelwartz** [comment] 2020-07-20 10:01
I'll close the issue until you provide more feedback as it seems very specific to your environment

**Comment by gnadelwartz** [comment] 2020-10-06 12:06
#154

**Comment by gnadelwartz** [comment] 2020-10-16 18:19
removed json.sh flag -s in development version, let's see if it works better...

**Comment by gnadelwartz** [comment] 2020-10-29 12:33
no response, let's close

**Closed by gnadelwartz** 2020-10-29 12:33 UTC
Labels: bug, review /test needed
